version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/adrianperdomoe/orders_system/app:latest
    ports:
      - "8080:8080"

  mongodb:
    build:
      context: ./mongoDB
      dockerfile: Dockerfile
    image: ghcr.io/adrianperdomoe/orders_system/mongodb:latest
    ports:
      - "27017:27017"

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: ghcr.io/adrianperdomoe/orders_system/redis:latest
    ports:
      - "6379:6379"