name: Publish Docker Images and Compose File

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Build # Define el entorno
    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Loguearse en GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Construir y subir todas las imágenes usando Docker Compose
      - name: Build and Push Images
        run: |
          docker compose build --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
                               --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \
                               --build-arg REDIS_HOST=${{ secrets.REDIS_HOST }} \
                               --build-arg REDIS_PORT=${{ secrets.REDIS_PORT }} \
                               --build-arg REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
                               --build-arg DOCKER_ENV=${{ secrets.DOCKER_ENV }} \
                               --build-arg DATABASE=${{ secrets.DATABASE }} \
                               --build-arg USERNAME=${{ secrets.USERNAME }} \
                               --build-arg MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
          docker compose push

      # Generar el archivo docker-compose.yml limpio
      - name: Generate docker-compose.yml
        run: |
          cat <<EOF > docker-compose.yml
          version: '3.8'

          services:
            app:
              image: ghcr.io/adrianperdomoe/orders_system/app:latest
              ports:
                - "8080:8080"

            mongodb:
              image: ghcr.io/adrianperdomoe/orders_system/mongodb:latest
              ports:
                - "27017:27017"

            redis:
              image: ghcr.io/adrianperdomoe/orders_system/redis:latest
              ports:
                - "6379:6379"
          EOF

      # Subir el archivo docker-compose.yml como artefacto
      - name: Upload docker-compose.yml
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: docker-compose.yml